### PR TITLE
Create BST.py

### PR DESCRIPTION
**Pull request by sakshi13-m**

### CODE REVIEW

**Comment by sakshi13-m** [comment]
hey hacktober site is showing Ineligible Repository 
to correct it in the About section of the repo add topic 'hacktoberfest' then it will work perfectly

**Comment by MJ95** [comment]
> hey hacktober site is showing Ineligible Repository
> to correct it in the About section of the repo add topic 'hacktoberfest' then it will work perfectly

> Hi I have added in About Section, is there anything else that I have to do? Do I still eliglible for this Hacktoberfest2020?

**Comment by sakshi13-m** [comment]
now it is eligible all set!!

**Comment by MJ95** [comment]
Thanks🙂

**Comment by sakshi13-m** [comment]
hey could you please add 'hacktober-accepted' in the label field here then only it is considered accepted

**Comment by MJ95** [comment]
hey please check now and let me know

**Comment by sakshi13-m** [comment]
image
here in the labels

**Comment by sakshi13-m** [comment]
Like this :->>>>
image

**Comment by MJ95** [comment]
Hey Sakshi, Please check now if its correct

**Comment by sakshi13-m** [comment]
yes thanks for updating!!

**Pull request merged**
